apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  selector:
    matchLabels:
      region: India
  template:
    metadata:
      labels:
        region: India
    spec:
      containers:
      - name: my-container
        image: deepak25404/ip-flask:v3
        ports:
        - containerPort: 5000
