apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc
spec:
  replicas: 3
  selector: 
    region: 'India'
  template:
    metadata:
      name: myapp3
      labels: 
        region: 'India'
        Team: 'Dev'
    spec:
      containers:
      - name: myapp
        image: deepak25404/ip-flask:v3

